version: "3"

services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    ports:
      - '3306:3306'

  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      COLUMNS: 80 # Set 80 columns for docker exec -it.
      # Mode info about xdebug https://wodby.com/docs/stacks/drupal/local/#xdebug
      # PHP_XDEBUG: 1
      # PHP_XDEBUG_DEFAULT_ENABLE: 1
      # PHP_XDEBUG_REMOTE_AUTOSTART: 1
      # PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
      # PHP_IDE_CONFIG: serverName=my-ide
      # PHP_XDEBUG_REMOTE_HOST: host.docker.internal # Docker 18.03+ Mac/Win
      # PHP_XDEBUG_REMOTE_LOG: /tmp/php-xdebug.log
      # PHP_XDEBUG_REMOTE_HOST: 172.17.0.1 # Linux
      # PHP_XDEBUG_REMOTE_HOST: 10.254.254.254 # macOS, Docker < 18.03
      # PHP_XDEBUG_REMOTE_HOST: 10.0.75.1 # Windows, Docker < 18.03
    volumes:
      - ./:/var/www/html
    extra_hosts:
      admin.dreyers.com: 216.255.65.112
      services.dreyers.com: 216.255.65.112
      services.nestleusa.com: 216.255.65.112
      cws.nestleusa.com: 216.255.65.112
  apache:
    image: wodby/apache:$APACHE_TAG
    container_name: "${PROJECT_NAME}_apache"
    depends_on:
      - php
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_BACKEND_HOST: php
      APACHE_VHOST_PRESET: php
      APACHE_DOCUMENT_ROOT: /var/www/html/docroot
    volumes:
      - ./:/var/www/html
    ports:
      - '80:80'
#  node:
#    image: kkarczmarczyk/node-yarn
#    container_name: "${PROJECT_NAME}_node"
#    volumes:
#      - ./:/var/www/html
#    working_dir: /var/www/html/docroot/themes/custom/haagendazs
#    command: "yarn run dev"
